In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("train.csv",header=None)

In [3]:
data.head()

,0,1,2,3,4,5,6,7,8
0,0,'591764470197723137','#Nepal #news Adding to Bhutanese Refugees Bh...,NaN,NaN,NaN,NaN,NaN,NaN
1,0,'591779538046218240',"""The massacre of people's movement says peace...",NaN,NaN,NaN,NaN,NaN,NaN
2,0,'591728244925210624',"""I'm lonely",maybe you're going to die without closing the...,"I'm going to die.""",NaN,NaN,NaN,NaN
3,0,'591774433926193152','#nepal #news 6 billion collection collection...,NaN,NaN,NaN,NaN,NaN,NaN
4,0,'591764472651386882','#Nepal #news Indian proposal to crash airpor...,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data = data.fillna(value=" ")

In [5]:
data["texts"] = data[2].map(str)+data[3].map(str)+data[4].map(str)+data[5].map(str)+data[6].map(str)+data[7].map(str)+data[8].map(str)

In [6]:
data.head()

,0,1,2,3,4,5,6,7,8,texts
0,0,'591764470197723137','#Nepal #news Adding to Bhutanese Refugees Bh...,,,,,,,'#Nepal #news Adding to Bhutanese Refugees Bh...
1,0,'591779538046218240',"""The massacre of people's movement says peace...",,,,,,,"""The massacre of people's movement says peace..."
2,0,'591728244925210624',"""I'm lonely",maybe you're going to die without closing the...,"I'm going to die.""",,,,,"""I'm lonely maybe you're going to die without..."
3,0,'591774433926193152','#nepal #news 6 billion collection collection...,,,,,,,'#nepal #news 6 billion collection collection...
4,0,'591764472651386882','#Nepal #news Indian proposal to crash airpor...,,,,,,,'#Nepal #news Indian proposal to crash airpor...

In [7]:
data = data.drop(columns=[2,3,4,5,6,7,8],axis = 1)

In [8]:
data["texts"][0]

" '#Nepal #news Adding to Bhutanese Refugees Bhutanese citizens of Nepalese origin still refrain from leaving their bags.'       "

In [9]:
from sklearn.feature_extraction import text

In [10]:
vect = text.TfidfVectorizer()

In [11]:
x = vect.fit(data["texts"])

In [12]:
abc =x.transform(data["texts"])

In [13]:
abc

<18086x17090 sparse matrix of type '<class 'numpy.float64'>'
	with 246565 stored elements in Compressed Sparse Row format>

In [14]:
vect.vocabulary_

{'nepal': 10096,
 'news': 10208,
 'adding': 823,
 'to': 15078,
 'bhutanese': 2244,
 'refugees': 12252,
 'citizens': 3129,
 'of': 10485,
 'nepalese': 10132,
 'origin': 10649,
 'still': 14144,
 'refrain': 12246,
 'from': 5927,
 'leaving': 8622,
 'their': 14879,
 'bags': 1784,
 'the': 14870,
 'massacre': 9206,
 'people': 11061,
 'movement': 9706,
 'says': 13085,
 'peace': 11029,
 'and': 1218,
 'constitution': 3482,
 'have': 6653,
 'lost': 8864,
 'in': 7280,
 'country': 3635,
 'lonely': 8835,
 'maybe': 9256,
 'you': 16638,
 're': 12119,
 'going': 6254,
 'die': 4339,
 'without': 16350,
 'closing': 3189,
 'city': 3130,
 'love': 8876,
 'will': 16315,
 'not': 10365,
 'leave': 8620,
 'billion': 2283,
 'collection': 3252,
 '12': 55,
 'one': 10542,
 'year': 16598,
 'half': 6530,
 '30': 225,
 'thousand': 14952,
 'foreign': 5812,
 'studies': 14239,
 'indian': 7336,
 'proposal': 11718,
 'crash': 3677,
 'airport': 1024,
 'crashes': 3679,
 'four': 5859,
 'days': 3923,
 'god': 6233,
 'also': 1114,
 'ran': 12041,
 'away': 1690,
 'for': 5795,
 'money': 9611,
 'after': 919,
 'poor': 11364,
 'listened': 8750,
 'what': 16253,
 'he': 6675,
 'asked': 1517,
 'someone': 13881,
 'feels': 5583,
 'like': 8710,
 'tile': 15017,
 'see': 13209,
 'boys': 2477,
 'began': 2015,
 'write': 16454,
 'english': 5113,
 'passage': 10962,
 'taw': 14655,
 'go': 6226,
 'it': 7675,
 'be': 1969,
 'broken': 2563,
 'because': 1988,
 'get': 6139,
 'gaurab': 6070,
 'sir': 13697,
 'is': 7638,
 'shaken': 13383,
 'as': 1482,
 'cheat': 3002,
 'why': 16299,
 'do': 4547,
 'cheats': 3004,
 'give': 6187,
 'us': 15747,
 'baba': 1726,
 'ramdev': 12022,
 'clean': 3154,
 'bagramati': 1783,
 'ray': 12109,
 'kiripur': 8310,
 'now': 10383,
 'can': 2739,
 'two': 15420,
 'plastic': 11244,
 'tip': 15050,
 'cleanbagmati': 3155,
 'seventh': 13337,
 'asian': 1513,
 'games': 6023,
 'madras': 8960,
 'bastasta': 1930,
 'won': 16378,
 'title': 15057,
 'janak': 7770,
 'yadav': 16572,
 'win': 16319,
 'gold': 6257,
 'pic': 11158,
 'annapurna': 1258,
 'http': 7057,
 'new': 10200,
 'updates': 15706,
 'started': 14091,
 'society': 13849,
 'san': 12949,
 'jose': 7929,
 'original': 10650,
 'by': 2676,
 'anjum': 1250,
 'rahbar': 11948,
 'used': 15755,
 'flame': 5709,
 'flames': 5710,
 'water': 16154,
 'came': 2724,
 'today': 15081,
 'excited': 5334,
 'river': 12625,
 'let': 8654,
 'compromise': 3381,
 'steal': 14130,
 'your': 16643,
 'temper': 14749,
 'miss': 9508,
 'memories': 9344,
 'my': 9829,
 'sleep': 13762,
 'gajendra': 6012,
 'received': 12179,
 'diary': 4323,
 'extremely': 5408,
 'beautiful': 1983,
 'writing': 16457,
 'on': 10538,
 'cover': 3655,
 'page': 10782,
 'wrote': 16465,
 'that': 14867,
 'medicine': 9310,
 'should': 13550,
 'mufti': 9767,
 'electric': 5006,
 'cheap': 3000,
 'autism': 1643,
 'children': 3041,
 'cooperate': 3573,
 'korea': 8381,
 'political': 11344,
 'science': 13126,
 'social': 13841,
 'sport': 14019,
 'good': 6271,
 'morning': 9647,
 'sheikh': 13459,
 'photo': 11139,
 'sent': 13284,
 'when': 16268,
 'are': 1416,
 'sitting': 13719,
 'dil': 4369,
 'queen': 11880,
 'castle': 2815,
 'mine': 9454,
 'we': 16183,
 'heavens': 6722,
 'am': 1125,
 'very': 15899,
 'happy': 6587,
 'hunter': 7110,
 'friend': 5910,
 'if': 7190,
 'wrap': 16436,
 'with': 16346,
 'then': 14889,
 'learn': 8614,
 'books': 2431,
 'literature': 8759,
 'just': 7984,
 'ask': 1516,
 'right': 12588,
 'all': 1081,
 'these': 14901,
 'tweets': 15409,
 'copyrighted': 3588,
 'day': 3920,
 'friends': 5914,
 'jai': 7719,
 'there': 14894,
 'lot': 8865,
 'sulfony': 14340,
 'general': 6103,
 'knowledge': 8360,
 'quiz': 11902,
 'nepali': 10138,
 'language': 8545,
 'lok': 8819,
 'sewa': 13345,
 'aayog': 678,
 'यज': 16980,
 'loksewanepal': 8827,
 'floors': 5739,
 'currently': 3796,
 'active': 793,
 'thank': 14833,
 'remove': 12372,
 'bird': 2299,
 'chest': 3019,
 'hajur': 6524,
 'subhash': 14266,
 'prabhat': 11441,
 'want': 16108,
 'another': 1280,
 'person': 11090,
 'freelance': 5894,
 'freak': 5882,
 'pre': 11520,
 'written': 16458,
 'mamtainsa12': 9095,
 'jaskaran57000': 7801,
 'beta': 2084,
 'this': 14928,
 'our': 10675,
 'food': 5779,
 'bank': 1856,
 'help': 6754,
 'disabilities': 4409,
 'fasting': 5521,
 'fast': 5517,
 'news11': 10209,
 'bishkek': 2310,
 'being': 2036,
 'japan': 7790,
 'self': 13240,
 'diagnose': 4315,
 'viruses': 15985,
 'jarcot': 7794,
 'kathmandu': 8130,
 'government': 6316,
 'jury': 7982,
 'again': 939,
 'suspicion': 14468,
 'most': 9662,
 'jars': 7798,
 'patients': 10992,
 'been': 2005,
 'diagnosed': 4316,
 'psychiatry': 11767,
 'jajarkot': 7734,
 'dum': 4738,
 'seasonal': 13179,
 'flu': 5748,
 'la': 8462,
 'kind': 8299,
 'earthquake': 4815,
 'juice': 7957,
 'released': 12320,
 'kauhlu': 8146,
 'harmful': 6608,
 'coward': 3661,
 'mixed': 9533,
 'sugarcane': 14321,
 'always': 1122,
 'wants': 16112,
 'eat': 4886,
 'whole': 16289,
 'they': 14902,
 'printed': 11629,
 'well': 16228,
 'oscar': 10662,
 'award': 1683,
 'सक': 17050,
 'security': 13205,
 'consultation': 3492,
 'planning': 11238,
 'plan': 11231,
 'dodhara': 4557,
 'congress': 3438,
 'interrupter': 7564,
 'issue': 7669,
 'vidya': 15945,
 'bhandari': 2152,
 'middle': 9418,
 'last': 8562,
 'ca': 2691,
 'second': 13184,
 'constituent': 3479,
 'assembly': 1531,
 'zoo': 16701,
 'anup': 1296,
 'possible': 11391,
 'think': 14912,
 'rupees': 12783,
 'night': 10265,
 'sleeping': 13765,
 'case': 2808,
 'execution': 5345,
 'exam_first': 5317,
 'pupils': 11803,
 'school': 13123,
 'students': 14238,
 'way': 16174,
 'tries': 15295,
 'tie': 15011,
 'taili': 14569,
 'proudnepali': 11744,
 'hinges': 6890,
 'ever': 5275,
 'tired': 15052,
 'third': 14917,
 'party': 10950,
 'tweet': 15403,
 'recently': 12183,
 'arrived': 1457,
 'gupta': 6449,
 'opposition': 10606,
 'leader': 8603,
 'ucpn': 15516,
 'maoist': 9152,
 'led': 8625,
 'no': 10310,
 'available': 1649,
 'annagree': 1257,
 'past': 10970,
 'daily': 3834,
 'maoists': 9153,
 'state': 14098,
 'xa0': 16486,
 'how': 7031,
 'much': 9763,
 'near': 10030,
 'ones': 10543,
 'talking': 14592,
 'close': 3184,
 'usual': 15769,
 'care': 2783,
 'where': 16270,
 'finished': 5672,
 'selling': 13252,
 'milk': 9436,
 'does': 4559,
 'value': 15820,
 'difficult': 4352,
 'produce': 11661,
 'farmers': 5505,
 'who': 16287,
 'vegetable': 15870,
 'sure': 14411,
 'apple': 1364,
 'blossom': 2393,
 'karnali': 8098,
 'got': 6306,
 'angry': 1238,
 'him': 6851,
 'me': 9269,
 'both': 2451,
 'wrinkle': 16453,
 'burning': 2642,
 'few': 5615,
 'notes': 10368,
 'khabar': 8211,
 'national': 9961,
 'burns': 2644,
 'almost': 1102,
 '70': 525,
 'years': 16599,
 'jugaad': 7954,
 'entered': 5133,
 'ear': 4786,
 'make': 9063,
 'tissue': 15056,
 'papar': 10878,
 'tablet': 14556,
 'put': 11838,
 'minute': 9475,
 'paper': 10879,
 'rt': 12735,
 'only': 10550,
 'gives': 6190,
 'such': 14288,
 'mandate': 9108,
 'sees': 13225,
 'thirsts': 14922,
 'anonymous': 1277,
 'bad': 1759,
 'teach': 14665,
 'job': 7895,
 'knew': 8351,
 'was': 16133,
 'would': 16429,
 'yourself': 16645,
 'touch': 15152,
 'corruption': 3608,
 'corrupt': 3607,
 'so': 13831,
 'killer': 8287,
 'murderer': 9804,
 'but': 2665,
 'said': 12889,
 'against': 940,
 'injustice': 7451,
 'grave': 6356,
 'haramam': 6594,
 'hurry': 7115,
 'more': 9644,
 'difficulty': 4353,
 'seen': 13222,
 'many': 9151,
 'deadly': 3942,
 'loved': 8878,
 'fill': 5647,
 'binny': 2292,
 'responded': 12487,
 'field': 5625,
 'taking': 14582,
 'ball': 1819,
 'bottle': 2455,
 'whopping': 16293,
 'violation': 15973,
 'rules': 12765,
 'icc': 7161,
 'rrvsrcb': 12726,
 'tell': 14739,
 'aine': 998,
 'play': 11253,
 'ruby': 12748,
 'jhapali': 7863,
 'jarrakot': 7797,
 'campaign': 2729,
 'treatment': 15254,
 'swine': 14517,
 'flint': 5729,
 'jararkot': 7793,
 'premier': 11551,
 'league': 8610,
 'ipl': 7609,
 'defeated': 4018,
 'royal': 12714,
 'challenger': 2931,
 'bankor': 1860,
 'roles': 12670,
 'wickets': 16301,
 'dot': 4613,
 'million': 9442,
 'husband': 7121,
 'lol': 8828,
 'cpn': 3667,
 'mlas': 9537,
 'mind': 9449,
 'll': 8783,
 'break': 2506,
 'before': 2011,
 'tomorrow': 15110,
 'sow': 13941,
 'scare': 13101,
 'dowry': 4635,
 'grow': 6398,
 'tree': 15258,
 'woods': 16388,
 'rakib': 12013,
 'hmmm': 6918,
 'hurts': 7120,
 'headache': 6678,
 'times': 15032,
 'pain': 10794,
 'feeling': 5579,
 'head': 6677,
 'wanna': 16107,
 'enjoy': 5119,
 'too': 15124,
 'saying': 13083,
 'say': 13080,
 'hi': 6813,
 'eating': 4891,
 'kettle': 8206,
 'pig': 11176,
 'include': 7302,
 'u000fe35b': 15463,
 'u000fe046': 15442,
 'pram': 11472,
 'premiere': 11552,
 'saturday': 13034,
 'saturn': 13036,
 'u000fe04e': 15443,
 'staying': 14121,
 'perfect': 11072,
 'lady': 8482,
 'drinking': 4676,
 'alcohol': 1067,
 'rajasthan': 11987,
 'royals': 12715,
 'bangalore': 1849,
 'top': 15130,
 'motorcycles': 9684,
 'butwal': 2670,
 'death': 3955,
 'palpa': 10825,
 'saddam': 12838,
 'tansen': 14622,
 'stone': 14159,
 'falling': 5473,
 'road': 12639,
 'baggati': 1777,
 'waste': 16141,
 'went': 16234,
 'off': 10488,
 'cleaned': 3156,
 'nep': 10094,
 'journalist': 7936,
 'america': 1153,
 'comment': 3299,
 'extent': 5395,
 'weekly': 16213,
 'columns': 3274,
 'taste': 14646,
 'things': 14911,
 'jaipur': 7725,
 'stop': 14164,
 'supply': 14387,
 'next': 10246,
 'month': 9625,
 'shutdown': 13589,
 'link': 8734,
 'up': 15699,
 'plant': 11240,
 'old': 10526,
 'age': 945,
 'shaheer': 13370,
 'those': 14944,
 'use': 15753,
 'muscle': 9812,
 'media': 9298,
 'power': 11421,
 'or': 10618,
 'abuse': 725,
 '360': 244,
 'u200b': 15481,
 'u200bseats': 15497,
 'kamala': 8053,
 'msg9successfulweeks': 9724,
 'heat': 6719,
 'has': 6619,
 'drink': 4672,
 'than': 14830,
 'avoid': 1671,
 'summer': 14347,
 'farmer': 5502,
 'kenya': 8197,
 'left': 8628,
 'grass': 6351,
 'killed': 8286,
 'cow': 3660,
 'sheep': 13453,
 'silk': 13646,
 'movie': 9711,
 'read': 12135,
 'perspective': 11097,
 'reshamfilili': 12456,
 'heartfelt': 6711,
 'greetings': 6370,
 '2072': 147,
 'nepalinewyear': 10141,
 'icosyo': 7168,
 'coming': 3288,
 'glory': 6216,
 'buddha': 2596,
 'nepalis': 10144,
 'even': 5269,
 'mood': 9632,
 'flown': 5747,
 'out': 10683,
 'quiet': 11896,
 'quietly': 11898,
 'lips': 8743,
 'keep': 8173,
 'covered': 3657,
 'rid': 12583,
 'global': 6209,
 'azure': 1711,
 'boot': 2434,
 'camp': 2728,
 'gabc': 5995,
 'at': 1569,
 'bhairai': 2127,
 'college': 3258,
 'know': 8357,
 'yu': 16655,
 'walk': 16095,
 'own': 10740,
 'system': 14547,
 'birth': 2304,
 'born': 2444,
 'regardless': 12263,
 'tactics': 14560,
 'become': 1990,
 'better': 2092,
 'democracy': 4087,
 'chief': 3035,
 'army': 1441,
 'staff': 14067,
 'pakistan': 10808,
 'headed': 6680,
 'prime': 11619,
 'minister': 9464,
 'gaurav': 6071,
 'shamser': 13407,
 'his': 6895,
 'pakistani': 10809,
 'counterpart': 3628,
 'saheel': 12882,
 'sarfko': 13007,
 'economic': 4904,
 'journalism': 7935,
 'talim': 14589,
 'dulkha': 4737,
 'control': 3539,
 'chitwan': 3060,
 'outbreak': 10687,
 'dengue': 4096,
 '11': 45,
 'chhattan': 3027,
 'disease': 4448,
 'bangladesh': 1853,
 'vijay': 15958,
 'iran': 7617,
 'organized': 10640,
 'organizers': 10641,
 'soccer': 13840,
 'mukesh': 9773,
 'dr': 4643,
 'govind': 6319,
 'kc': 8166,
 'goal_nepal': 6230,
 'le': 8601,
 'clock': 3180,
 'killing': 8290,
 'activist': 796,
 'subin': 14267,
 'mehmud': 9330,
 'friday': 5905,
 'human': 7079,
 'rights': 12591,
 'karachi': 8084,
 'import': 7260,
 'imports': 7263,
 'stopping': 14168,
 'thinking': 14914,
 'first': 5687,
 'drowned': 4696,
 'died': 4340,
 'separate': 13292,
 'incident': 7298,
 'different': 4349,
 'parts': 10949,
 'defeat': 4017,
 'india': 7329,
 'join': 7905,
 'final': 5658,
 'illiterate': 7222,
 'present': 11569,
 'dream': 4658,
 'dreams': 4660,
 'filled': 5648,
 'tapping': 14629,
 'someday': 13879,
 'sunny': 14364,
 'rate': 12078,
 'change': 2955,
 'down': 4626,
 'leone': 8646,
 'puzzle': 11844,
 'leela': 8627,
 'featuring': 5566,
 'animated': 1247,
 'distribution': 4507,
 'educational': 4931,
 'materials': 9228,
 'bagmati': 1781,
 'safi': 12864,
 'pride': 11614,
 'yogguru': 16629,
 '8d': 570,
 'dalit': 3847,
 'child': 3037,
 'could': 3617,
 'she': 13448,
 'vaashakh': 15794,
 'sandhuli': 12957,
 'five': 5700,
 'reign': 12291,
 'republican': 12416,
 'hundreds': 7105,
 'commonwealth': 3319,
 'committees': 3312,
 'celebrated': 2862,
 'cultural': 3786,
 'committee': 3311,
 'save': 13052,
 'vishnu': 15993,
 'poudel': 11411,
 'great': 6358,
 'leaders': 8604,
 'parties': 10945,
 'nephew': 10176,
 'sighted': 13615,
 'bikaner': 2276,
 'breaking': 2510,
 'resistance': 12468,
 'negligence': 10065,
 'officials': 10503,
 'jaldhayi': 7746,
 'department': 4110,
 'over': 10710,
 'dozen': 4637,
 'climbed': 3172,
 'tank': 14619,
 'girl': 6180,
 'opening': 10570,
 'incense': 7294,
 'baashakh': 1724,
 'taplejung': 14626,
 'thermal': 14898,
 'following': 5773,
 'afc': 892,
 'women': 16376,
 'football': 5789,
 'academy': 733,
 'pokhara': 11326,
 'dainnath': 3837,
 'baral': 1877,
 'awarded': 1684,
 'public': 11777,
 'traffic': 15195,
 'coordination': 3580,
 'kamers': 8058,
 'campus': 2737,
 'bba': 1953,
 'th': 14814,
 'sem': 13256,
 'question': 11884,
 'weightlessness': 16220,
 'about': 701,
 'effective': 4960,
 'gravity': 6357,
 'zero': 16687,
 'ice': 7162,
 'malaysia': 9078,
 'known': 8362,
 'workers': 16396,
 'u1': 15474,
 'paratha': 10900,
 'foodventures': 5781,
 'dhadu': 4257,
 'hisila': 6897,
 'yami': 16580,
 'anary': 1212,
 'honorable': 6968,
 'barcelona': 1879,
 'spain': 13948,
 'chile': 3043,
 'international': 7557,
 'level': 8663,
 'swimming': 14516,
 'pool': 11363,
 'police': 11337,
 'vehicle': 15873,
 'bought': 2461,
 '52': 328,
 'three': 14966,
 'months': 9627,
 'increasing': 7318,
 'trade': 15191,
 'jarkarkot': 7796,
 'feedback': 5573,
 'support': 14390,
 'supporting': 14394,
 'ashok': 1497,
 'dinda': 4383,
 'takes': 14581,
 'sunlight': 14361,
 'clouds': 3196,
 'hide': 6816,
 'which': 16276,
 'cold': 3235,
 'runner': 12776,
 'runs': 12778,
 'breaks': 2513,
 'rightnow': 12590,
 'senior': 13266,
 'singer': 13677,
 'prem': 11548,
 'prakash': 11470,
 'malla': 9086,
 'madhukar': 8954,
 'passed': 10963,
 'liked': 8711,
 'pizza': 11219,
 'hotel': 7012,
 'home': 6951,
 'mother': 9667,
 'hand': 6554,
 'together': 15087,
 'saif': 12890,
 'ali': 1074,
 'khan': 8234,
 'shahid': 13371,
 'kapoor': 8079,
 'mumbai': 9790,
 'shah': 13367,
 'generations': 6108,
 'ha': 6495,
 'spoke': 14011,
 'place': 11226,
 'named': 9895,
 'swiss': 14523,
 'feel': 5577,
 'famerscrying': 5481,
 'did': 4335,
 'incoming': 7308,
 'lambs': 8518,
 'waiting': 16081,
 'sister': 13705,
 'asking': 1518,
 'pounds': 11414,
 'blood': 2384,
 'dyeing': 4777,
 'hurt': 7116,
 'sorry': 13915,
 'sn': 13815,
 'rainfall': 11973,
 'janakpur': 7772,
 'weather': 16201,
 'rainy': 11976,
 'rain': 11971,
 'raining': 11974,
 'visited': 16003,
 'ago': 963,
 'yoga': 16627,
 'kitipur': 8339,
 'owner': 10742,
 'intercontinental': 7546,
 'lord': 8852,
 'om': 10531,
 'ram': 12017,
 'communication': 3327,
 'policy': 11341,
 'goes': 6248,
 'through': 14975,
 'communications': 3328,
 'fund': 5963,
 'damash': 3856,
 'baikhakh': 1792,
 'prachanda': 11445,
 'bring': 2547,
 'proud': 11742,
 'gadhakdar': 6001,
 'republic': 12414,
 'newsstreet': 10237,
 'liberty': 8676,
 'anyway': 1314,
 'able': 697,
 'otherwise': 10669,
 'any': 1306,
 'other': 10667,
 'sangeeta': 12966,
 'tamang': 14601,
 'kuala': 8419,
 'lumpur': 8908,
 'penang': 11053,
 'vacation': 15798,
 'slightly': 13773,
 'appreciate': 1373,
 'sunil': 14360,
 'dispersed': 4471,
 'program': 11675,
 'babu': 1735,
 'listen': 8749,
 'stay': 14115,
 'europe': 5248,
 'deaths': 3957,
 'bihar': 2266,
 'cyclone': 3810,
 'squirrel': 14046,
 'rahul': 11956,
 'gandhi': 6028,
 'may': 9253,
 'contest': 3512,
 '14': 71,
 'girls': 6183,
 'regional': 12272,
 'cham': 2935,
 'cable': 2695,
 'line': 8728,
 'seriously': 13302,
 'injured': 7446,
 'were': 16237,
 'accident': 747,
 'dating': 3912,
 'loss': 8862,
 'relationship': 12308,
 'john': 7903,
 'abraham': 706,
 'actress': 805,
 'disappointed': 4416,
 'prachand': 11444,
 'dissatisfaction': 4488,
 'peaceful': 11030,
 'calm': 2718,
 'sea': 13168,
 'face': 5422,
 'inside': 7490,
 'tidal': 15009,
 'bhut': 2242,
 'waves': 16169,
 'sarita': 13011,
 'oli': 10529,
 'uml': 15545,
 'chairman': 2913,
 'kp': 8396,
 'sharma': 13430,
 'absolute': 711,
 'word': 16391,
 'carpus': 2795,
 'roof': 12679,
 'house': 7022,
 'granule': 6345,
 'vessel': 15901,
 'warm': 16121,
 'bit': 2317,
 'thin': 14909,
 'platelet': 11247,
 'bag': 1775,
 'area': 1417,
 'under': 15577,
 'issued': 7670,
 'capital': 2770,
 'playing': 11258,
 'rejected': 12295,
 'team': 14671,
 'pragmatism': 11458,
 'felt': 5591,
 'kolkata': 8375,
 'महम': 16976,
 'tremors': 15275,
 'lucknow': 8902,
 'fierce': 5628,
 'huge': 7068,
 'dhanbad': 4265,
 'bokaro': 2413,
 'jharkhand': 7865,
 'within': 16349,
 'come': 3279,
 'mahendranagar': 9028,
 'an': 1197,
 'patna': 10994,
 'jhapa': 7862,
 'ma': 8932,
 'take': 14577,
 'tinairlai': 15043,
 'open': 10567,
 'eyes': 5414,
 'shouted': 13556,
 'laughing': 8580,
 'tremendous': 15271,
 'delhi': 4060,
 'happeningnow': 6581,
 'shocks': 13530,
 'due': 4730,
 'common': 3316,
 'man': 9096,
 'fault': 5535,
 'fir': 5676,
 'demanded': 4081,
 'punishment': 11799,
 'aaprallymurder': 664,
 'aapkisanrally': 662,
 'secular': 13197,
 ...}

In [15]:
stopwords = vect.stop_words_

In [16]:
data['texts'] = data['texts'].apply(lambda x: [item for item in str.split(x) if item not in stopwords])

In [17]:
data.head()

   0                      1                                              texts
0  0   '591764470197723137'  ['#Nepal, #news, Adding, to, Bhutanese, Refuge...
1  0   '591779538046218240'  ["The, massacre, of, people's, movement, says,...
2  0   '591728244925210624'  ["I'm, lonely, maybe, you're, going, to, die, ...
3  0   '591774433926193152'  ['#nepal, #news, 6, billion, collection, colle...
4  0   '591764472651386882'  ['#Nepal, #news, Indian, proposal, to, crash, ...

In [20]:
for item in stopwords:
    print(item)